name: Check CPL rc/rc/rc

on:
  schedule:
    - cron: "0 11 * * *"
  workflow_dispatch:

jobs:
  build-config:
    name: CPL rc/rc/rc
    uses: ./.github/workflows/check-pl-compat.yml
    with:
      catalyst: release-candidate
      pennylane: release-candidate
      lightning: release-candidate
